project:
  type: website
  output-dir: docs

website:
  title: "ExESS"
  search: true
  navbar:
    background: primary
    left:
      - text: "Home"
        href: src/index.qmd
      - text: "Documentation"
        href: src/documentation.qmd
      - text: "Wiki"
        href: src/wiki.qmd
      - text: "Manual"
        href: src/manual.qmd
      - text: "API"
        href: src/api.qmd

  sidebar:
    - title: "Home"
      style: docked
      background: light
      contents:
        - text: "Home"
          href: src/index.qmd

    - title: "Documentation"
      style: docked
      background: light
      contents:
        - text: "Documentation"
          href: src/documentation.qmd

    - title: "Wiki"
      style: docked
      background: light
      contents:
        - src/wiki.qmd

    - title: "Manual"
      style: docked
      background: light
      contents:
        - src/manual.qmd

    - title: "API"
      style: docked
      background: light
      contents:
        - src/api.qmd

format:
  html:
    theme: flatly
    # theme: sandstone
    css: styles.css
    toc: true



