

::: {.callout-note collapse="true" #label}
# Derivation of spherical Laplace operator.

The laplacian is the linear summation of the second-order cartesian partial derivative $\nabla^2 = \frac{\partial^2}{\partial\cartesianCoordinateX^2} + \frac{\partial^2}{\partial\cartesianCoordinateY^2} + \frac{\partial^2}{\partial\cartesianCoordinateZ^2}$. The spherical laplacian can be derived by applying the chain rule of partial derivatives, shown in the gradient derivation in Eqs. \eqref{eq:spherical_gradient_x}, \eqref{eq:spherical_gradient_y}, \eqref{eq:spherical_gradient_z} twice:
\begin{align*}
    \frac{\partial^2}{\partial\cartesianCoordinateX^2} &= \cos\sphericalCoordinateAzimuth\cos\sphericalCoordinateElevation\frac{\partial}{\partial\sphericalCoordinateRadius}\frac{\partial}{\partial\cartesianCoordinateX} -\frac{\sin\sphericalCoordinateAzimuth}{\sphericalCoordinateRadius\cos\sphericalCoordinateElevation} \frac{\partial}{\partial\sphericalCoordinateAzimuth}\frac{\partial}{\partial\cartesianCoordinateX} -\frac{\cos\sphericalCoordinateAzimuth\sin\sphericalCoordinateElevation}{\sphericalCoordinateRadius} \frac{\partial}{\partial\sphericalCoordinateElevation}\frac{\partial}{\partial\cartesianCoordinateX} \\
    &= \cos\sphericalCoordinateAzimuth\cos\sphericalCoordinateElevation\frac{\partial}{\partial\sphericalCoordinateRadius} \left( \cos\sphericalCoordinateAzimuth\cos\sphericalCoordinateElevation\frac{\partial}{\partial\sphericalCoordinateRadius} -\frac{\sin\sphericalCoordinateAzimuth}{\sphericalCoordinateRadius\cos\sphericalCoordinateElevation} \frac{\partial}{\partial\sphericalCoordinateAzimuth} -\frac{\cos\sphericalCoordinateAzimuth\sin\sphericalCoordinateElevation}{\sphericalCoordinateRadius} \frac{\partial}{\partial\sphericalCoordinateElevation}\right) \\
    &- \frac{\sin\sphericalCoordinateAzimuth}{\sphericalCoordinateRadius\cos\sphericalCoordinateElevation} \frac{\partial}{\partial\sphericalCoordinateAzimuth} \left( \cos\sphericalCoordinateAzimuth\cos\sphericalCoordinateElevation\frac{\partial}{\partial\sphericalCoordinateRadius} -\frac{\sin\sphericalCoordinateAzimuth}{\sphericalCoordinateRadius\cos\sphericalCoordinateElevation} \frac{\partial}{\partial\sphericalCoordinateAzimuth} -\frac{\cos\sphericalCoordinateAzimuth\sin\sphericalCoordinateElevation}{\sphericalCoordinateRadius} \frac{\partial}{\partial\sphericalCoordinateElevation} \right) \\
    &- \frac{\cos\sphericalCoordinateAzimuth\sin\sphericalCoordinateElevation}{\sphericalCoordinateRadius} \frac{\partial}{\partial\sphericalCoordinateElevation} \left( \cos\sphericalCoordinateAzimuth\cos\sphericalCoordinateElevation\frac{\partial}{\partial\sphericalCoordinateRadius} -\frac{\sin\sphericalCoordinateAzimuth}{\sphericalCoordinateRadius\cos\sphericalCoordinateElevation} \frac{\partial}{\partial\sphericalCoordinateAzimuth} -\frac{\cos\sphericalCoordinateAzimuth\sin\sphericalCoordinateElevation}{\sphericalCoordinateRadius} \frac{\partial}{\partial\sphericalCoordinateElevation} \right) \\
    %
    \frac{\partial^2}{\partial\cartesianCoordinateY^2} &= \sin\sphericalCoordinateAzimuth\cos\sphericalCoordinateElevation\frac{\partial}{\partial\sphericalCoordinateRadius}\frac{\partial}{\partial\cartesianCoordinateY} + \frac{\cos\sphericalCoordinateAzimuth}{\sphericalCoordinateRadius\cos\sphericalCoordinateElevation} \frac{\partial}{\partial\sphericalCoordinateAzimuth}\frac{\partial}{\partial\cartesianCoordinateY} -\frac{\sin\sphericalCoordinateAzimuth\sin\sphericalCoordinateElevation}{\sphericalCoordinateRadius} \frac{\partial}{\partial\sphericalCoordinateElevation}\frac{\partial}{\partial\cartesianCoordinateY} \\
    &= \sin\sphericalCoordinateAzimuth\cos\sphericalCoordinateElevation\frac{\partial}{\partial\sphericalCoordinateRadius} \left( \sin\sphericalCoordinateAzimuth\cos\sphericalCoordinateElevation\frac{\partial}{\partial\sphericalCoordinateRadius} + \frac{\cos\sphericalCoordinateAzimuth}{\sphericalCoordinateRadius\cos\sphericalCoordinateElevation} \frac{\partial}{\partial\sphericalCoordinateAzimuth} -\frac{\sin\sphericalCoordinateAzimuth\sin\sphericalCoordinateElevation}{\sphericalCoordinateRadius} \frac{\partial}{\partial\sphericalCoordinateElevation} \right) \\
    &+ \frac{\cos\sphericalCoordinateAzimuth}{\sphericalCoordinateRadius\cos\sphericalCoordinateElevation} \frac{\partial}{\partial\sphericalCoordinateAzimuth} \left( \sin\sphericalCoordinateAzimuth\cos\sphericalCoordinateElevation\frac{\partial}{\partial\sphericalCoordinateRadius} + \frac{\cos\sphericalCoordinateAzimuth}{\sphericalCoordinateRadius\cos\sphericalCoordinateElevation} \frac{\partial}{\partial\sphericalCoordinateAzimuth} -\frac{\sin\sphericalCoordinateAzimuth\sin\sphericalCoordinateElevation}{\sphericalCoordinateRadius} \frac{\partial}{\partial\sphericalCoordinateElevation} \right) \\
    &- \frac{\sin\sphericalCoordinateAzimuth\sin\sphericalCoordinateElevation}{\sphericalCoordinateRadius} \frac{\partial}{\partial\sphericalCoordinateElevation} \left( \sin\sphericalCoordinateAzimuth\cos\sphericalCoordinateElevation\frac{\partial}{\partial\sphericalCoordinateRadius} + \frac{\cos\sphericalCoordinateAzimuth}{\sphericalCoordinateRadius\cos\sphericalCoordinateElevation} \frac{\partial}{\partial\sphericalCoordinateAzimuth} -\frac{\sin\sphericalCoordinateAzimuth\sin\sphericalCoordinateElevation}{\sphericalCoordinateRadius} \frac{\partial}{\partial\sphericalCoordinateElevation} \right) \\
    %
    \frac{\partial^2}{\partial\cartesianCoordinateZ^2} &= \sin\sphericalCoordinateElevation\frac{\partial}{\partial\sphericalCoordinateRadius}\frac{\partial}{\partial\cartesianCoordinateZ} + \frac{\cos\sphericalCoordinateElevation}{\sphericalCoordinateRadius} \frac{\partial}{\partial\sphericalCoordinateElevation}\frac{\partial}{\partial\cartesianCoordinateZ} \\
    &= \sin\sphericalCoordinateElevation\frac{\partial}{\partial\sphericalCoordinateRadius} \left( -\sin\sphericalCoordinateElevation\frac{\partial}{\partial\sphericalCoordinateRadius} + \frac{\cos\sphericalCoordinateElevation}{\sphericalCoordinateRadius} \frac{\partial}{\partial\sphericalCoordinateElevation} \right) + \frac{\cos\sphericalCoordinateElevation}{\sphericalCoordinateRadius} \frac{\partial}{\partial\sphericalCoordinateElevation} \left( -\sin\sphericalCoordinateElevation\frac{\partial}{\partial\sphericalCoordinateRadius} + \frac{\cos\sphericalCoordinateElevation}{\sphericalCoordinateRadius} \frac{\partial}{\partial\sphericalCoordinateElevation} \right).
\end{align*}
Evaluating all partial derivatives and summing up all terms leads to a miraculous cancellation of terms, finally arriving at the following expression of Eq.~(\ref{eq:laplace_spherical}) for the Laplacian in spherical coordinates:
\begin{align*}
    \nabla^2 &= \frac{\partial^2}{\partial\sphericalCoordinateRadius^2} + \frac{2}{\sphericalCoordinateRadius}\frac{\partial}{\partial\sphericalCoordinateRadius} + \frac{1}{\sphericalCoordinateRadius^2\cos^2\sphericalCoordinateElevation}\frac{\partial}{\partial\sphericalCoordinateAzimuth} + \frac{1}{\sphericalCoordinateRadius^2} \frac{\partial^2}{\partial\sphericalCoordinateElevation^2} - \frac{\sin\sphericalCoordinateElevation}{\sphericalCoordinateRadius^2\cos\sphericalCoordinateElevation} \frac{\partial}{\partial\sphericalCoordinateElevation} \\
    &= \frac{1}{\sphericalCoordinateRadius^2}\frac{\partial}{\partial\sphericalCoordinateRadius}\left(\sphericalCoordinateRadius^2\frac{\partial}{\partial\sphericalCoordinateRadius}\right) + \frac{1}{\sphericalCoordinateRadius^2\cos^2\sphericalCoordinateElevation}\frac{\partial}{\partial\sphericalCoordinateAzimuth} + \frac{1}{\sphericalCoordinateRadius^2\cos\sphericalCoordinateElevation} \frac{\partial}{\partial\sphericalCoordinateElevation} \left(\cos\sphericalCoordinateElevation\frac{\partial}{\partial\sphericalCoordinateElevation}\right).
\end{align*}
:::