---
title: "2.1.2 -- Coordinate Differentials"
code-tools: false
---

<!-- LaTeX Commands -->
\newcommand{\base}{\hat{\mathbf{e}}}

::: {.collapse}
a
:::


<!-- Text -->
This work is regularly relying on vector calculus which includes a substantial use of differentials and derivatives. The former uses two kinds of notations, depending on the use case of the differential. First, mathematical differentials of vectors are the vectorized form of the differentials of the vector components. In the following, the differentials will be set up for stationary conditions with constant base vectors, i.e.

::: {.panel-tabset}
## Equation
\begin{align}
    \frac{\partial}{\partial t} &= 0 \\
    \frac{\partial\base{e}_x}{\partial r} &= \frac{\partial\base{e}_x}{\partial\theta} = \frac{\partial\base{e}_x}{\partial\phi} = \frac{\partial\base{e}_y}{\partial r} = \frac{\partial\base{e}_y}{\partial\theta} = \frac{\partial\base{e}_y}{\partial\phi} = \frac{\partial\base{e}_z}{\partial r} = \frac{\partial\base{e}_z}{\partial\theta} = \frac{\partial\base{e}_z}{\partial\phi} = 0 \\
    \frac{\partial\base{e}_r}{\partial x} &= \frac{\partial\base{e}_r}{\partial y} = \frac{\partial\base{e}_r}{\partial z} = \frac{\partial\base{e}_\theta}{\partial x} = \frac{\partial\base{e}_\theta}{\partial y} = \frac{\partial\base{e}_\theta}{\partial z} = \frac{\partial\base{e}_\phi}{\partial x} = \frac{\partial\base{e}_\phi}{\partial y} = \frac{\partial\base{e}_\phi}{\partial z} = 0
\end{align}

## Code

```latex
\newcommand{\base}{\hat{\mathbf{e}}}
\begin{align}
    \frac{\partial}{\partial t} &= 0 \\
    \frac{\partial\base{e}_x}{\partial r} &= \frac{\partial\base{e}_x}{\partial\theta} = \frac{\partial\base{e}_x}{\partial\phi} = \frac{\partial\base{e}_y}{\partial r} = \frac{\partial\base{e}_y}{\partial\theta} = \frac{\partial\base{e}_y}{\partial\phi} = \frac{\partial\base{e}_z}{\partial r} = \frac{\partial\base{e}_z}{\partial\theta} = \frac{\partial\base{e}_z}{\partial\phi} = 0 \\
    \frac{\partial\base{e}_r}{\partial x} &= \frac{\partial\base{e}_r}{\partial y} = \frac{\partial\base{e}_r}{\partial z} = \frac{\partial\base{e}_\theta}{\partial x} = \frac{\partial\base{e}_\theta}{\partial y} = \frac{\partial\base{e}_\theta}{\partial z} = \frac{\partial\base{e}_\phi}{\partial x} = \frac{\partial\base{e}_\phi}{\partial y} = \frac{\partial\base{e}_\phi}{\partial z} = 0
\end{align}
```
:::


For example, the differential of a stationary cartesian coordinate vector and cartesian elements is
\begin{equation}
    d\mathbf{x} = \frac{\partial\mathbf{x}}{\partial x}dx + \frac{\partial\mathbf{x}}{\partial y}d y + \frac{\partial\mathbf{x}}{\partial z}dz = dx \base{x} + d y \base{y} + d z \base{z} = \begin{bmatrix} d x \\ d y \\ d z \end{bmatrix},
\end{equation}
and for spherical coordinates and elements
\begin{equation}
    d\sphericalCoordinate = \frac{\partial\sphericalCoordinate}{\partial\sphericalCoordinateRadius}d\sphericalCoordinateRadius + \frac{\partial\sphericalCoordinate}{\partial\sphericalCoordinateAzimuth}d\sphericalCoordinateAzimuth + \frac{\partial\sphericalCoordinate}{\partial\sphericalCoordinateElevation}d\sphericalCoordinateElevation = d\sphericalCoordinateRadius \sphericalBaseVectorRadius + d\sphericalCoordinateAzimuth \sphericalBaseVectorAzimuth + d\sphericalCoordinateElevation \sphericalBaseVectorElevation = \begin{bmatrix} d\sphericalCoordinateRadius \\ d\sphericalCoordinateAzimuth \\ d\sphericalCoordinateElevation \end{bmatrix}.
\end{equation}